/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mycompany.oop;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author jairus
 */
public class Activity1 extends javax.swing.JFrame {

    /**
     * Creates new form Activity1
     */
    public Activity1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        mother1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        FN1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        MN1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        mother2 = new javax.swing.JTextField();
        CN2 = new javax.swing.JTextField();
        FN2 = new javax.swing.JTextField();
        MN2 = new javax.swing.JTextField();
        LN2 = new javax.swing.JTextField();
        age2 = new javax.swing.JTextField();
        gender2 = new javax.swing.JTextField();
        address2 = new javax.swing.JTextField();
        father2 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel18 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel20 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel21 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel22 = new javax.swing.JLabel();
        LN1 = new javax.swing.JTextField();
        age1 = new javax.swing.JTextField();
        gender1 = new javax.swing.JTextField();
        CN1 = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        father1 = new javax.swing.JTextField();
        CloseBtn = new javax.swing.JButton();
        CopyBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        javax.swing.JLabel jLabel23 = new javax.swing.JLabel();
        bday2 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel24 = new javax.swing.JLabel();
        bday1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ilacio_Activity1");
        setMaximumSize(new java.awt.Dimension(925, 775));
        setMinimumSize(new java.awt.Dimension(925, 775));
        setPreferredSize(new java.awt.Dimension(925, 775));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\jairus\\Downloads\\Icons (50 x 50 px) (1).png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 110, 80, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(977, 150));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\jairus\\Downloads\\Icons (50 x 50 px).png")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 20, 50, 50);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("National University MOA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 20, 271, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 930, 85);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -5, 1150, 90);

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 28)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Personal Information");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 190, 320, 34);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setText("First Name: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 260, 150, 30);
        getContentPane().add(mother1);
        mother1.setBounds(180, 620, 260, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setText("Mother's name:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 620, 150, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setText("First Name: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 260, 150, 30);

        FN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FN1ActionPerformed(evt);
            }
        });
        getContentPane().add(FN1);
        FN1.setBounds(180, 260, 260, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setText("Last Name: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 340, 150, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel9.setText("Last Name: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 340, 150, 30);

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel10.setText("Middle Name: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(470, 300, 150, 30);

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel11.setText("Age: ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 380, 150, 30);

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel12.setText("Gender: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 460, 150, 30);

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel13.setText("Contact Number: ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 500, 150, 30);

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel14.setText("Address: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 540, 150, 30);

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel15.setText("Father's name:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 580, 150, 30);

        MN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MN1ActionPerformed(evt);
            }
        });
        getContentPane().add(MN1);
        MN1.setBounds(180, 300, 260, 30);

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel16.setText("Contact Number: ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(470, 500, 150, 30);

        mother2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mother2.setEnabled(false);
        mother2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mother2ActionPerformed(evt);
            }
        });
        getContentPane().add(mother2);
        mother2.setBounds(620, 620, 260, 30);

        CN2.setToolTipText("");
        CN2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CN2.setEnabled(false);
        CN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CN2ActionPerformed(evt);
            }
        });
        getContentPane().add(CN2);
        CN2.setBounds(620, 500, 260, 30);

        FN2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        FN2.setEnabled(false);
        FN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FN2ActionPerformed(evt);
            }
        });
        getContentPane().add(FN2);
        FN2.setBounds(620, 260, 260, 30);

        MN2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        MN2.setEnabled(false);
        MN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MN2ActionPerformed(evt);
            }
        });
        getContentPane().add(MN2);
        MN2.setBounds(620, 300, 260, 30);

        LN2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        LN2.setEnabled(false);
        LN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LN2ActionPerformed(evt);
            }
        });
        getContentPane().add(LN2);
        LN2.setBounds(620, 340, 260, 30);

        age2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        age2.setEnabled(false);
        age2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age2ActionPerformed(evt);
            }
        });
        getContentPane().add(age2);
        age2.setBounds(620, 380, 260, 30);

        gender2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        gender2.setEnabled(false);
        gender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender2ActionPerformed(evt);
            }
        });
        getContentPane().add(gender2);
        gender2.setBounds(620, 460, 260, 30);

        address2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        address2.setEnabled(false);
        address2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address2ActionPerformed(evt);
            }
        });
        getContentPane().add(address2);
        address2.setBounds(620, 540, 260, 30);

        father2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        father2.setEnabled(false);
        father2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                father2ActionPerformed(evt);
            }
        });
        getContentPane().add(father2);
        father2.setBounds(620, 580, 260, 30);

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel17.setText("Middle Name: ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 300, 150, 30);

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel18.setText("Age: ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(470, 380, 150, 30);

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel19.setText("Gender: ");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(470, 460, 150, 30);

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel20.setText("Address: ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(470, 540, 150, 30);

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel21.setText("Father's name:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(470, 580, 150, 30);

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel22.setText("Mother's name:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(470, 620, 150, 30);
        getContentPane().add(LN1);
        LN1.setBounds(180, 340, 260, 30);

        age1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age1ActionPerformed(evt);
            }
        });
        age1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                age1KeyPressed(evt);
            }
        });
        getContentPane().add(age1);
        age1.setBounds(180, 380, 260, 30);
        getContentPane().add(gender1);
        gender1.setBounds(180, 460, 260, 30);

        CN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CN1ActionPerformed(evt);
            }
        });
        CN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CN1KeyPressed(evt);
            }
        });
        getContentPane().add(CN1);
        CN1.setBounds(180, 500, 260, 30);
        getContentPane().add(address1);
        address1.setBounds(180, 540, 260, 30);
        getContentPane().add(father1);
        father1.setBounds(180, 580, 260, 30);

        CloseBtn.setBackground(new java.awt.Color(255, 51, 51));
        CloseBtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.setFocusPainted(false);
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBtn);
        CloseBtn.setBounds(580, 680, 90, 30);

        CopyBtn.setBackground(new java.awt.Color(102, 255, 102));
        CopyBtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        CopyBtn.setText("Copy");
        CopyBtn.setFocusPainted(false);
        CopyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CopyBtn);
        CopyBtn.setBounds(240, 680, 90, 30);

        ClearBtn.setBackground(new java.awt.Color(255, 204, 51));
        ClearBtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        ClearBtn.setText("Clear");
        ClearBtn.setFocusPainted(false);
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ClearBtn);
        ClearBtn.setBounds(410, 680, 90, 30);

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel23.setText("Birthday: ");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(30, 420, 150, 30);

        bday2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bday2.setEnabled(false);
        bday2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bday2ActionPerformed(evt);
            }
        });
        getContentPane().add(bday2);
        bday2.setBounds(620, 420, 260, 30);

        jLabel24.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel24.setText("Birthday: ");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(470, 420, 150, 30);

        bday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bday1ActionPerformed(evt);
            }
        });
        bday1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bday1KeyPressed(evt);
            }
        });
        getContentPane().add(bday1);
        bday1.setBounds(180, 420, 260, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FN1ActionPerformed

    private void MN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MN1ActionPerformed

    private void mother2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mother2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mother2ActionPerformed

    private void CN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CN2ActionPerformed

    private void FN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FN2ActionPerformed

    private void MN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MN2ActionPerformed

    private void LN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LN2ActionPerformed

    private void age2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age2ActionPerformed

    private void gender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender2ActionPerformed

    private void address2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address2ActionPerformed

    private void father2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_father2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_father2ActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void CopyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyBtnActionPerformed
        if (!areFieldsEmptyOrNull()) {

            if (CN1.getText().matches("^09\\d{9}$")) {
                FN2.setText(FN1.getText());
                MN2.setText(MN1.getText());
                LN2.setText(LN1.getText());
                age2.setText(age1.getText());
                bday2.setText(bday1.getText());
                gender2.setText(gender1.getText());
                CN2.setText(CN1.getText());
                address2.setText(address1.getText());
                father2.setText(father1.getText());
                mother2.setText(mother1.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Please enter valid contact number", "Invalid Contact Number", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please fill up every information field needed", "Incomplete Information", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_CopyBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
        FN1.setText("");
        FN2.setText("");
        MN1.setText("");
        MN2.setText("");
        LN1.setText("");
        LN2.setText("");
        age1.setText("");
        age2.setText("");
        bday1.setText("");
        bday2.setText("");
        gender1.setText("");
        gender2.setText("");
        CN1.setText("");
        CN2.setText("");
        address1.setText("");
        address2.setText("");
        father1.setText("");
        father2.setText("");
        mother1.setText("");
        mother2.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void age1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age1KeyPressed
        // TODO add your handling code here:

        char keyChar = evt.getKeyChar();
        if (Character.isDigit(keyChar) || keyChar == KeyEvent.VK_BACK_SPACE) {
            age1.setEditable(true);
        } else {
            age1.setEditable(false);
        }
    }//GEN-LAST:event_age1KeyPressed


    private void CN1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CN1KeyPressed
        // TODO add your handling code here:
        String value = CN1.getText();
        int l = value.length();
        if (l >= 11 && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) {
            CN1.setEditable(false);
            JOptionPane.showMessageDialog(null, "Accepts 11-digit number only!", "Invalid Contact Number!", JOptionPane.ERROR_MESSAGE);
            CN1.requestFocus();
        }

        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            CN1.setEditable(true);
        } else {
            CN1.setEditable(false);
        }


    }//GEN-LAST:event_CN1KeyPressed

    private void bday2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bday2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bday2ActionPerformed

    private void CN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CN1ActionPerformed

    private void age1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age1ActionPerformed

    private void bday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bday1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bday1ActionPerformed

    private void bday1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bday1KeyPressed
        char keyChar = evt.getKeyChar();
        if (Character.isDigit(keyChar) || keyChar == KeyEvent.VK_BACK_SPACE || keyChar == '-') {
            bday1.setEditable(true);
        } else {
            bday1.setEditable(false);
        }
    }//GEN-LAST:event_bday1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity1().setVisible(true);
            }
        });
    }

    private boolean areFieldsEmptyOrNull() {
        return FN1 == null || FN1.getText().trim().isEmpty()
                || LN1 == null || LN1.getText().trim().isEmpty()
                || MN1 == null || MN1.getText().trim().isEmpty()
                || address1 == null || address1.getText().trim().isEmpty()
                || age1 == null || age1.getText().trim().isEmpty()
                || father1 == null || father1.getText().trim().isEmpty()
                || gender1 == null || gender1.getText().trim().isEmpty();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CN1;
    private javax.swing.JTextField CN2;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton CopyBtn;
    private javax.swing.JTextField FN1;
    private javax.swing.JTextField FN2;
    private javax.swing.JTextField LN1;
    private javax.swing.JTextField LN2;
    private javax.swing.JTextField MN1;
    private javax.swing.JTextField MN2;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField address2;
    private javax.swing.JTextField age1;
    private javax.swing.JTextField age2;
    private javax.swing.JTextField bday1;
    private javax.swing.JTextField bday2;
    private javax.swing.JTextField father1;
    private javax.swing.JTextField father2;
    private javax.swing.JTextField gender1;
    private javax.swing.JTextField gender2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mother1;
    private javax.swing.JTextField mother2;
    // End of variables declaration//GEN-END:variables
}